apiVersion: v1
kind: Config
clusters:
- cluster:
    api-version: v1
    certificate-authority-data: a
    server: "https://b"
  name: "local"
contexts:
- context:
    cluster: "local"
    user: "kube-admin-local"
  name: "local"
current-context: "local"
users:
- name: "kube-admin-local"
  user:
    client-certificate-data: e
    client-key-data: d